import type { PartnerProduct } from './partnerApi';

// DEMO DATA — same isDemo convention as Overview/Orders: shown only while
// this store's real product list is empty, so Inventory is never a blank
// page during setup. Gone the instant one real product is added.
export const DEMO_PRODUCTS: PartnerProduct[] = [
  // One product, three sizes — the exact "Onion 500 g / 1 kg / 2 kg" case:
  // a single row in the table (see InventoryTable's VariantPrices), never
  // three duplicate "Onion" rows.
  {
    id: 'demo-product-0',
    name: 'Onion',
    local_name: null,
    category: 'Vegetables',
    description: null,
    price: 15,
    original_price: null,
    image_url: null,
    is_veg: true,
    freshness_tag: 'Fresh today',
    is_in_stock: true,
    stock_status: 'in_stock',
    approval_status: 'approved',
    product_variants: [
      { id: 'demo-v0a', unit_type: 'g', quantity: 500, price: 15, original_price: null, is_default: true },
      { id: 'demo-v0b', unit_type: 'kg', quantity: 1, price: 28, original_price: 32, is_default: false },
      { id: 'demo-v0c', unit_type: 'kg', quantity: 2, price: 54, original_price: null, is_default: false },
    ],
  },
  {
    id: 'demo-product-1',
    name: 'Amul Fresh Milk',
    local_name: null,
    category: 'Dairy',
    description: null,
    price: 58,
    original_price: null,
    image_url: null,
    is_veg: true,
    freshness_tag: 'Fresh today',
    is_in_stock: true,
    stock_status: 'in_stock',
    approval_status: 'approved',
    product_variants: [{ id: 'demo-v1', unit_type: 'ml', quantity: 500, price: 58, original_price: null, is_default: true }],
  },
  {
    id: 'demo-product-2',
    name: 'Britannia Bread',
    local_name: null,
    category: 'Bakery',
    description: null,
    price: 49,
    original_price: 55,
    image_url: null,
    is_veg: true,
    freshness_tag: null,
    is_in_stock: true,
    stock_status: 'in_stock',
    approval_status: 'approved',
    product_variants: [{ id: 'demo-v2', unit_type: 'g', quantity: 400, price: 49, original_price: 55, is_default: true }],
  },
  {
    id: 'demo-product-3',
    name: 'Tata Salt',
    local_name: null,
    category: 'Staples',
    description: null,
    price: 22,
    original_price: null,
    image_url: null,
    is_veg: true,
    freshness_tag: null,
    is_in_stock: true,
    stock_status: 'in_stock',
    approval_status: 'approved',
    product_variants: [{ id: 'demo-v3', unit_type: 'kg', quantity: 1, price: 22, original_price: null, is_default: true }],
  },
  {
    id: 'demo-product-4',
    name: 'Maggi Noodles',
    local_name: null,
    category: 'Instant food',
    description: null,
    price: 65,
    original_price: 72,
    image_url: null,
    is_veg: true,
    freshness_tag: null,
    is_in_stock: true,
    stock_status: 'in_stock',
    approval_status: 'approved',
    product_variants: [{ id: 'demo-v4', unit_type: 'pc', quantity: 2, price: 65, original_price: 72, is_default: true }],
  },
  {
    id: 'demo-product-5',
    name: 'Red Label Tea',
    local_name: null,
    category: 'Beverages',
    description: null,
    price: 130,
    original_price: null,
    image_url: null,
    is_veg: true,
    freshness_tag: null,
    is_in_stock: true,
    stock_status: 'in_stock',
    approval_status: 'approved',
    product_variants: [{ id: 'demo-v5', unit_type: 'g', quantity: 250, price: 130, original_price: null, is_default: true }],
  },
  {
    id: 'demo-product-6',
    name: 'Aashirvaad Atta',
    local_name: null,
    category: 'Staples',
    description: null,
    price: 285,
    original_price: null,
    image_url: null,
    is_veg: true,
    freshness_tag: null,
    is_in_stock: false,
    stock_status: 'out_of_stock',
    approval_status: 'approved',
    product_variants: [{ id: 'demo-v6', unit_type: 'kg', quantity: 5, price: 285, original_price: null, is_default: true }],
  },
  {
    id: 'demo-product-7',
    name: 'Fortune Sunflower Oil',
    local_name: null,
    category: 'Staples',
    description: null,
    price: 195,
    original_price: 210,
    image_url: null,
    is_veg: true,
    freshness_tag: null,
    is_in_stock: false,
    stock_status: 'out_of_stock',
    approval_status: 'approved',
    product_variants: [{ id: 'demo-v7', unit_type: 'l', quantity: 1, price: 195, original_price: 210, is_default: true }],
  },
  {
    id: 'demo-product-8',
    name: 'Local Farm Eggs (6-pack)',
    local_name: null,
    category: 'Dairy',
    description: null,
    price: 48,
    original_price: null,
    image_url: null,
    is_veg: false,
    freshness_tag: 'New',
    is_in_stock: true,
    stock_status: 'in_stock',
    approval_status: 'pending',
    product_variants: [{ id: 'demo-v8', unit_type: 'pc', quantity: 6, price: 48, original_price: null, is_default: true }],
  },
];
