// Shared config pattern — copied (not npm-linked) into each of the 3 RN apps.
// Source: specs/00-foundation/repo-structure.md
const expoConfig = require('eslint-config-expo/flat');

// ios/Pods — vendored CocoaPods dependency source (generated by `pod
// install`/`expo run:ios`, not app code) — only exists in this app
// (partner/rider have no ios/ directory at all). eslint-config-expo/flat
// doesn't ignore it by default; without this, its minified vendor JS
// (minified vendor pod JS) fails to even parse.
module.exports = [{ ignores: ['ios/Pods/**', 'android/**'] }, ...expoConfig];
